# Generated by selenium IDE
import pytest
# ##import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.common.exceptions import NoSuchElementException

class TestGetImageFromInput:
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.wait = WebDriverWait(self.driver, 10)
    
    def teardown_method(self, method):
        self.driver.quit()

    def test_get_image_from_input(self, search_term="ai generative"):
        self.driver.get("https://duckduckgo.com/")
        self.driver.maximize_window()
        
        try:
            search_input = self.wait.until(EC.element_to_be_clickable((By.ID, "searchbox_input")))
            search_input.send_keys(search_term)
            search_input.send_keys(Keys.ENTER)

            images_link = self.wait.until(EC.element_to_be_clickable((By.LINK_TEXT, "Images")))
            images_link.click()

            # Validate that the Images page has loaded with results
            assert "Images" in self.driver.title
        except NoSuchElementException as e:
            print(f"Error during test execution: {str(e)}")

if __name__ == "__main__":
    test = TestGetImageFromInput()
    test.setup_method(None)
    test.test_get_image_from_input()
    test.teardown_method(None)

